<?php
name: WitheredFactionKits
main: WFkits\Main
version: 0.0.1
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: POSTWORLD
author: David2020xD
description: Kits.
commands:
	wizard:
		description: "get a wand."
		permission: op
permissions:
	wizard.kit:
    defualt: op
    description: "get a wand"
    children:
